export const arkitBlendshapeMap = new Map<string, string | ''>([
    //brow
    ['browInnerUp', ''],
    ['browDownLeft', 'browDown_L'],
    ['browDownRight', 'browDown_R'],
    ['browOuterUpLeft', 'browOuterUp_L'],
    ['browOuterUpRight', 'browOuterUp_R'],
    //eye
    ['eyeLookUpLeft', 'eyeLookUp_L'],
    ['eyeLookUpRight', 'eyeLookUp_R'],
    ['eyeLookDownLeft', 'eyeLookDown_L'],
    ['eyeLookDownRight', 'eyeLookDown_R'],
    ['eyeLookInLeft', 'eyeLookIn_L'],
    ['eyeLookInRight', 'eyeLookIn_R'],
    ['eyeLookOutLeft', 'eyeLookOut_L'],
    ['eyeLookOutRight', 'eyeLookOut_R'],
    ['eyeBlinkLeft', 'eyeBlink_L'],
    ['eyeBlinkRight', 'eyeBlink_R'],
    ['eyeSquintLeft', 'eyeSquint_L'],
    ['eyeSquintRight', 'eyeSquint_R'],
    ['eyeWideLeft', 'eyeWide_L'],
    ['eyeWideRight', 'eyeWide_R'],
    //cheek
    ['cheekPuff', 'cheekPuff'],
    ['cheekSquintLeft', ''],
    ['cheekSquintRight', ''],
    //nose
    ['noseSneerLeft', 'noseSneer_L'],
    ['noseSneerRight', 'noseSneer_R'],
    //mouth
    ['mouthFunnel', 'mouthFunnel'],
    ['mouthPucker', 'mouthPucker'],
    ['mouthRollUpper', 'mouthRollUpper'],
    ['mouthRollLower', 'mouthRollLower'],
    ['mouthShrugUpper', 'mouthShrugUpper'],
    ['mouthShrugLower', ''],
    ['mouthClose', ''],
    ['mouthSmileLeft', 'mouthSmile_L'],
    ['mouthSmileRight', 'mouthSmile_R'],
    ['mouthFrownLeft', 'mouthFrown_L'],
    ['mouthFrownRight', 'mouthFrown_R'],
    ['mouthDimpleLeft', ''],
    ['mouthDimpleRight', ''],
    ['mouthUpperUpLeft', 'mouthUpperUp_L'],
    ['mouthUpperUpRight', 'mouthUpperUp_R'],
    ['mouthLowerDownLeft', 'mouthLowerDown_L'],
    ['mouthLowerDownRight', 'mouthLowerDown_R'],
    ['mouthPressLeft', ''],
    ['mouthPressRight', ''],
    ['mouthStretchLeft', ''],
    ['mouthStretchRight', ''],
    ['mouthLeft', 'mouthLeft'],
    ['mouthRight', 'mouthRight'],
    //jaw
    ['jawOpen', 'jawOpen'],
    ['jawForward', ''],
    ['jawLeft', 'jawLeft'],
    ['jawRight', 'jawRight'],
    //tongue
    ['tongueOut', 'tongueOut'],
]);

export const arkitBlendshapeName = [
    "browInnerUp",
    "browDownLeft",
    "browDownRight",
    "browOuterUpLeft",
    "browOuterUpRight",
    "eyeLookUpLeft",
    "eyeLookUpRight",
    "eyeLookDownLeft",
    "eyeLookDownRight",
    "eyeLookInLeft",
    "eyeLookInRight",
    "eyeLookOutLeft",
    "eyeLookOutRight",
    "eyeBlinkLeft",
    "eyeBlinkRight",
    "eyeSquintLeft",
    "eyeSquintRight",
    "eyeWideLeft",
    "eyeWideRight",
    "cheekPuff",
    "cheekSquintLeft",
    "cheekSquintRight",
    "noseSneerLeft",
    "noseSneerRight",
    "mouthFunnel",
    "mouthPucker",
    "mouthRollUpper",
    "mouthRollLower",
    "mouthShrugUpper",
    "mouthShrugLower",
    "mouthClose",
    "mouthSmileLeft",
    "mouthSmileRight",
    "mouthFrownLeft",
    "mouthFrownRight",
    "mouthDimpleLeft",
    "mouthDimpleRight",
    "mouthUpperUpLeft",
    "mouthUpperUpRight",
    "mouthLowerDownLeft",
    "mouthLowerDownRight",
    "mouthPressLeft",
    "mouthPressRight",
    "mouthStretchLeft",
    "mouthStretchRight",
    "mouthLeft",
    "mouthRight",
    "jawOpen",
    "jawForward",
    "jawLeft",
    "jawRight",
    "tongueOut"
]

export const mocapBlendshapeNames = [
    'browOuterUp_L',
    'browInnerUp_L',
    'browDown_L',
    'eyeBlink_L',
    'eyeSquint_L',
    'eyeWide_L',
    'eyeLookUp_L',
    'eyeLookOut_L',
    'eyeLookIn_L',
    'eyeLookDown_L',
    'noseSneer_L',
    'mouthUpperUp_L',
    'mouthSmile_L',
    'mouthLeft',
    'mouthFrown_L',
    'mouthLowerDown_L',
    'jawLeft',
    'cheekPuff',
    'mouthShrugUpper',
    'mouthFunnel',
    'mouthRollLower',
    'jawOpen',
    'tongueOut',
    'mouthPucker',
    'mouthRollUpper',
    'jawRight',
    'mouthLowerDown_R',
    'mouthFrown_R',
    'mouthRight',
    'mouthSmile_R',
    'mouthUpperUp_R',
    'noseSneer_R',
    'eyeLookDown_R',
    'eyeLookIn_R',
    'eyeLookOut_R',
    'eyeLookUp_R',
    'eyeWide_R',
    'eyeSquint_R',
    'eyeBlink_R',
    'browDown_R',
    'browInnerUp_R',
    'browOuterUp_R',
];

export const mediapipeBlendshapes = [
    '_neutral',
    'browDownLeft',
    'browDownRight',
    'browInnerUp',
    'browOuterUpLeft',
    'browOuterUpRight',
    'cheekPuff',
    'cheekSquintLeft',
    'cheekSquintRight',
    'eyeBlinkLeft',
    'eyeBlinkRight',
    'eyeLookDownLeft',
    'eyeLookDownRight',
    'eyeLookInLeft',
    'eyeLookInRight',
    'eyeLookOutLeft',
    'eyeLookOutRight',
    'eyeLookUpLeft',
    'eyeLookUpRight',
    'eyeSquintLeft',
    'eyeSquintRight',
    'eyeWideLeft',
    'eyeWideRight',
    'jawForward',
    'jawLeft',
    'jawOpen',
    'jawRight',
    'mouthClose',
    'mouthDimpleLeft',
    'mouthDimpleRight',
    'mouthFrownLeft',
    'mouthFrownRight',
    'mouthFunnel',
    'mouthLeft',
    'mouthLowerDownLeft',
    'mouthLowerDownRight',
    'mouthPressLeft',
    'mouthPressRight',
    'mouthPucker',
    'mouthRight',
    'mouthRollLower',
    'mouthRollUpper',
    'mouthShrugLower',
    'mouthShrugUpper',
    'mouthSmileLeft',
    'mouthSmileRight',
    'mouthStretchLeft',
    'mouthStretchRight',
    'mouthUpperUpLeft',
    'mouthUpperUpRight',
    'noseSneerLeft',
    'noseSneerRight'
];